### PR TITLE
Ifc Test Changes

### PR DESCRIPTION
**Pull request by Clockwork-Muse**
Okay, _this_ is the set of tests I recommend using.  You'll have a couple of build errors (because you don't override a method for the return type), need to change one constructor (so that `of(year, month, day) can take leap day/year day), and then work all the failing tests (100+, although some of this is API changes, not actual problems in your code).

This is to bring how your tests look in line with existing efforts, and to make the API better behaved.

### CODE REVIEW

**Comment by Clockwork-Muse** [comment]
Actually, the correct answer was to make the line:

    {InternationalFixedDate.of(5, 1, 1), LocalDate.of(5, 1, 1)},

This is because what I'm really testing at that point is year changeover, from 4 to 5, so making the start of year 4 isn't helpful.
That commit is old though - it's fixed in the last one ("Correct errors in test data/code").

I don't have time at the moment, but I'll work the change for leap-day later.

**Comment by Clockwork-Muse** [comment]
<raises eyebrow>
While I'll fully admit to not running the tests at the point I made those commits, it's a little... unusual to comment on old, superseded commits.  You never know, the problems may have been fixed in another one.
Like I did.  
The whole point was to pass you a set of tests where any failures were significant (ie, something you needed to change in your implementation code, not the test code).  So _of course_ I ran the tests before submitting the PR, to make sure that any failures that resulted were significant.
While I'm not so arrogant as to think that what I gave you was completely without error (given I was handing you something that was failing anyways...and I actually did find more errors during the checks this time), I am confident (and arrogant) enough to think it's _significantly_ without error.

About `get(DAY_OF_WEEK)` (and I think you meant Thursday, not Friday, but...) - 
that wasn't a mistake in the sense that it was an accident.  That choice was deliberate.
My read of `java.time.DayOfWeek` and `java.time.temporal.ChronoField.DAY_OF_WEEK`, coupled with the fact that Year Day and Leap Day aren't an actual day of week, was that it meant that Iso and Fixed weren't aligned in terms of days of the week, and that renumbering should probably take place.  After all, Iso Thursday only matches Fixed Thursday every 5~6 years (and even then, only for half the year...).  The days share the same name, but that's unimportant compared to the fact that they aren't really aligned.
Now, that's my interpretation.  I could be wrong here - my recommendation, if you still think they should be aligned is to ask the main Stephen for clarification, and then change/leave the relevant tests yourself.

**Comment by catull** [comment]
Patches were applied manually, while files were changed, too.

**Comment by Clockwork-Muse** [comment]
Uh, I get you were applying patches manually.  What I can't figure out is why you'd bother.

You need to override `with(TemporalAdjuster)`, so the return type matches the _behavior-required implementation override_ of `with(TemporalField, newValue)`.  You should also be overriding `minus(...)`, for the same reason.
Changing all instances of `date` to `fixed` resulted in things being changed that shouldn't have.

Even ignoring the whole `DAY_OF_WEEK` thing (you'll need to convince me of your interpretation, or get owner approval), you're still failing some of the tests.
You also seem to be operating under a misconception.  I'm providing this file as a drop-in replacement, not as a list of suggestions.  Your current approach tests some things more often than they needed to be, and some things less often than they should have been (and some not at all, which is where you're still getting failures).  I changed the tests specifically to make it closer to the existing tests for other calendars, for two reasons:

 1. To make it easier for reviewers to spot differences, making it easier to spot what's special about this calendar.
 2. To help present a unified look to the library code.

I've resynced my code, fixed a couple more errors (that were easier to spot now that you've fixed some things), added one test (look for a `TODO:`, please), and reuploaded it.  If you can reopen this pull request, do so, or just pull the changes into your branch.  Work everything that isn't `DAY_OF_WEEK` (`ALIGNED_DAY_OF_WEEK_IN_MONTH`, etc, are **not** `DAY_OF_WEEK`), and then either convince me your interpretation of that value is correct (and change the tests yourself), or bring your code in line with my interpretation.

**Comment by catull** [comment]
The reason for the manual patch application is that the PR cannot be automatically merged.
This is what it states:

    We can’t automatically merge this pull request.
    Use the command line to resolve conflicts before continuing.

And it states the same now that I reopened the PR.
The icon "Merge pull request" is grayed out, so the CLI is the only option.

**Comment by catull** [comment]
Okay, ready for review.
Your test class was taken verbatim; 4 parts had to be changed.

I misinterpreted the DAY_OF_WEEK part - they are not week-days such as Monday, Tuesday etc, but instead "day 1 of the week", "day 2 of the week" etc.

Checked all the changes in my branch; how is your verdict ?

Thanks for your dedication and constructive criticism, must have been hard.

**Comment by Clockwork-Muse** [comment]
First, I need to apologize for some things:

 1. I've been heading towards viewing some aspects of this more as a "need to be right", rather than actually making sure I _am_ right.  I'm sorry I've been confrontational and bullheaded over some of this.
 2. I'm sorry for passing a test file with more errors than there should have been (less than 10/10%, but still more than it should have been).  My hubris made me overlook some things.

Now then ...
I've resynced and updated my file again, and force-pushed so a simple merge pull should work.  Most of this was to bring some formatting and comments in line with other examples (I'm afraid my autoformatter got away from me when I gave you the original file).  I'm curious to know what your usual process is, because most of the command line results I'm aware of seem to work on the final file differences, rather than on individual commits.  About your comments:
 - I'm kicking myself over missing the `.equals()` problem, as the summary view I use displays it nicely.  I was getting too focused on failures.
 - You're correct about line 436
 - You're probably correct about line 439 (I mean, the one included in `java.time` doesn't, which means it was probably intended as an extreme upper-bound value, and not something specific, but it's reasonable to get a more concrete value).
 - I think we were both wrong about 440: The correct result should be `ValueRange.of(-1, 0, 13, 13)`, as the upper bound of months for any year is always 13 (this keeps throwing me, too).
 - Proleptic year/invalid era tests have been split, meaning two different errors need to be thrown, one of which is `ClassCastException`.  (Side note, I know what you meant by that comment, but the specific wording seems a bit off: like that was the result you - potentially accidently - ended up with, so that's what you made the test look for, which would be somewhat backwards.  Instead of having deliberately made it throw that error). 
- Right about 1031/1032, nice catch.

This file was meant to be a replacement... at the time I created the pull request.  Once you started working the errors and updating your tests, it became less of an issue, especially sometime in the second round.  Once you finally caught on to what some of the tests were really looking for (like 1031/1032), you actually had some decent additions, including some comment tweaks.  I've gone back and put some of them back in, because I think they help make certain details more obvious.

I also added one test that's currently failing (besides updating 440), as there's a slight weakness in your current implementation.  You should be able to spot it.

Oh, why'd you change away from `'Leap Day'`/`'Year Day'` in `toString()`?  I thought that was fine.  I didn't touch that as part of the formatting updates, but you might consider putting it back in

After this, the fun stuff starts - next level of review of the date/chronology code!
Oh, I've been using [these settings](https://gist.github.com/f52b1b6f849e7c840c7e) for the Eclipse formatter for this project (somewhat different than what I'm used to, which is why it got away from me this time around - I forgot to change to these settings!), if you're able to make use of the file.

**Comment by catull** [comment]
InternationalFixedDate#toString() is English-only, whereas the numeric current solution covers many more "Locale"s.

And the switch of separators ('-' -> '/') is to avoid 'N--1--1' or 'N-0-1-0-1'; the last one is when I let AbstractDate deal with it. Does not look appealing.  The new code now always uses two digits for month and day-of-month, except for Year Day.  that way, Leap and Year day stick out.

Of all the other descendants of AbstractDate, only DiscordianDate overrides #toString(), to distinguish St. Tib's Day from other dates.  How you given it some thought how to handle different Locales ?
(Jour de S. Tib, Dia de S Tib, St. Tib-Tag, S. Tib, ....).

In light of missing Locale support in toString() - I have no solution yet, it is a good thing to look as close as possible to what AbstractDate#toString() renders.  You sold me the idea of implementing the special days as -1 and 0, to be interpreted in the constructors - I originally rejected the idea.

Have been using Eclipse when it was VisualAge for Java; have been refocussing on IntelliJ IDEA now.
Haven't tweaked the code formatter yet, but I will next.

Thanks again for the review.

**Comment by Clockwork-Muse** [comment]
Oh no, I agree with the separator change, if you switch to numeric-only.
`toString()` (in general, not just for this project) is usually meant for _debugging related_ output, not localized/formatted output.  For one thing, localization and formatting is usually orthogonal to the underlying type - dates shouldn't know about kanji (Chinese characters), and which one represents `MONTH`, after all.

In the base library, you'd probably normally instantiate `java.time.format.DateTimeFormatterBuilder`, then provide a custom map for any relevant fields. (although from the look of things, that might give problems with parsing year/leap day in this case...)

**Comment by catull** [comment]
My wish is to pass an InternationalFixedDate to SimpleDateFormat and either using the JVM's current Locale or accepting a Locale, to then render it.  With a hack it works in Java 8.

**Comment by Clockwork-Muse** [comment]
...hack indeed, given `SimpleDateFormat` won't take any of the new date/time types, beyond its other inherent problems (like not being concurrent-access safe).  You'd have to convert to `java.util.Date` first, which at minimum would eat any non-hour offset (if you had one attached).

**Comment by catull** [comment]
The hack I implemented is a lot simpler.

Say I wanted to support English Locales.
For each one of them, I have to provide a class FormatData_{LOCALE}.
So I invent a Locale en_ifc -> sun.text.resources.en.FormatData_en_ifc.

The class has to look like this:

```java
public class FormatData_en_ifc extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][] {
                { "NumberPatterns",
                        new String[] {
                                "#,##0.###;-#,##0.###", // decimal pattern
                                "\u00A4#,##0.00;-\u00A4#,##0.00", // currency pattern
                                "#,##0%" // percent pattern
                        }
                },
                { "DateTimePatternChars","GyMdkHmsSEDFwWahKzZ" },
                { "MonthNames",
                        new String[] { "January", "February", "March", "April", "May", "June", "Sol", "July", "August", "September", "October", "November", "December" } },
                { "MonthAbbreviations",
                        new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Sol", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" } }

        };
    }
}
```

However, the solution is in crafting something along the lines of
```java
   sun/util/resources/cldr/en/CalendarData_en_Dsrt_US.class
```
Yepp, undocumented, not to be messed with ...

**Pull request merged**
